// GENERATED — do not edit by hand.
//   node scripts/check-catalogue.mjs --write
//
// The hub is a separate Worker and cannot import the tool packages, so this is a
// copy of their page lists. The check script imports the real modules and fails
// if this drifts. Sources of truth:
//   tools/calculator/src/lib/calcs/index.ts  (ALL_CALCS)
//   tools/pdf/src/content.ts                 (TOOLS)
//   tools/image/src/content.ts               (PAIRS) + the 4 core pages below
//   tools/qr/src/content.ts                  (QR_TYPES, SYMBOLOGIES, PAYMENT_GUIDES)

export type Entry = [slug: string, label: string];

export const CALC: Entry[] = [
  ["loan-calculator", "Loan Calculator"],
  ["mortgage-calculator", "Mortgage Calculator"],
  ["auto-loan-calculator", "Auto Loan Calculator"],
  ["interest-calculator", "Simple Interest Calculator"],
  ["compound-interest-calculator", "Compound Interest Calculator"],
  ["payment-calculator", "Payment Calculator"],
  ["amortization-calculator", "Amortization Calculator"],
  ["retirement-calculator", "Retirement Calculator"],
  ["investment-calculator", "Investment Calculator"],
  ["inflation-calculator", "Inflation Calculator"],
  ["sales-tax-calculator", "Sales Tax Calculator"],
  ["tip-calculator", "Tip Calculator"],
  ["discount-calculator", "Discount Calculator"],
  ["bmi-calculator", "BMI Calculator"],
  ["bmr-calculator", "BMR Calculator"],
  ["calorie-calculator", "Calorie Calculator"],
  ["body-fat-calculator", "Body Fat Calculator"],
  ["ideal-weight-calculator", "Ideal Weight Calculator"],
  ["pace-calculator", "Pace Calculator"],
  ["due-date-calculator", "Due Date Calculator"],
  ["scientific-calculator", "Scientific Calculator"],
  ["percentage-calculator", "Percentage Calculator"],
  ["fraction-calculator", "Fraction Calculator"],
  ["random-number-generator", "Random Number Generator"],
  ["standard-deviation-calculator", "Standard Deviation Calculator"],
  ["mean-median-mode-calculator", "Mean, Median, Mode Calculator"],
  ["triangle-calculator", "Triangle Calculator"],
  ["gpa-calculator", "GPA Calculator"],
  ["grade-calculator", "Final Grade Calculator"],
  ["age-calculator", "Age Calculator"],
  ["date-calculator", "Date Calculator"],
  ["time-calculator", "Time Calculator"],
  ["hours-calculator", "Hours Calculator"],
  ["unit-converter", "Unit Converter"],
  ["square-footage-calculator", "Square Footage Calculator"],
  ["concrete-calculator", "Concrete Calculator"],
  ["subnet-calculator", "IP Subnet Calculator"],
  ["password-generator", "Password Generator"],
  ["kwsp-epf-calculator", "KWSP EPF Calculator (Malaysia)"],
  ["socso-eis-calculator", "SOCSO & EIS Calculator (Malaysia)"],
  ["pcb-calculator", "PCB Income Tax Calculator (Malaysia)"],
  ["malaysia-salary-calculator", "Malaysia Salary Calculator"],
  ["salary-calculator", "Salary Calculator (Hourly ↔ Annual)"],
  ["us-salary-tax-calculator", "United States Salary Calculator"],
  ["uk-salary-tax-calculator", "United Kingdom Salary Calculator"],
  ["singapore-salary-tax-calculator", "Singapore Salary Calculator"],
  ["australia-salary-tax-calculator", "Australia Salary Calculator"],
  ["india-salary-tax-calculator", "India Salary Calculator"],
  ["germany-salary-tax-calculator", "Germany Salary Calculator"],
  ["canada-salary-tax-calculator", "Canada Salary Calculator"],
  ["japan-salary-tax-calculator", "Japan Salary Calculator"],
];

export const CALC_CATEGORY: Record<string, string> = {
  ["loan-calculator"]: "Financial",
  ["mortgage-calculator"]: "Financial",
  ["auto-loan-calculator"]: "Financial",
  ["interest-calculator"]: "Financial",
  ["compound-interest-calculator"]: "Financial",
  ["payment-calculator"]: "Financial",
  ["amortization-calculator"]: "Financial",
  ["retirement-calculator"]: "Financial",
  ["investment-calculator"]: "Financial",
  ["inflation-calculator"]: "Financial",
  ["sales-tax-calculator"]: "Financial",
  ["tip-calculator"]: "Everyday",
  ["discount-calculator"]: "Everyday",
  ["bmi-calculator"]: "Health & Fitness",
  ["bmr-calculator"]: "Health & Fitness",
  ["calorie-calculator"]: "Health & Fitness",
  ["body-fat-calculator"]: "Health & Fitness",
  ["ideal-weight-calculator"]: "Health & Fitness",
  ["pace-calculator"]: "Health & Fitness",
  ["due-date-calculator"]: "Health & Fitness",
  ["scientific-calculator"]: "Math & Numbers",
  ["percentage-calculator"]: "Math & Numbers",
  ["fraction-calculator"]: "Math & Numbers",
  ["random-number-generator"]: "Math & Numbers",
  ["standard-deviation-calculator"]: "Math & Numbers",
  ["mean-median-mode-calculator"]: "Math & Numbers",
  ["triangle-calculator"]: "Math & Numbers",
  ["gpa-calculator"]: "Math & Numbers",
  ["grade-calculator"]: "Math & Numbers",
  ["age-calculator"]: "Date & Time",
  ["date-calculator"]: "Date & Time",
  ["time-calculator"]: "Date & Time",
  ["hours-calculator"]: "Date & Time",
  ["unit-converter"]: "Everyday",
  ["square-footage-calculator"]: "Everyday",
  ["concrete-calculator"]: "Everyday",
  ["subnet-calculator"]: "Everyday",
  ["password-generator"]: "Everyday",
  ["kwsp-epf-calculator"]: "Salary & Tax",
  ["socso-eis-calculator"]: "Salary & Tax",
  ["pcb-calculator"]: "Salary & Tax",
  ["malaysia-salary-calculator"]: "Salary & Tax",
  ["salary-calculator"]: "Salary & Tax",
  ["us-salary-tax-calculator"]: "Salary & Tax",
  ["uk-salary-tax-calculator"]: "Salary & Tax",
  ["singapore-salary-tax-calculator"]: "Salary & Tax",
  ["australia-salary-tax-calculator"]: "Salary & Tax",
  ["india-salary-tax-calculator"]: "Salary & Tax",
  ["germany-salary-tax-calculator"]: "Salary & Tax",
  ["canada-salary-tax-calculator"]: "Salary & Tax",
  ["japan-salary-tax-calculator"]: "Salary & Tax",
};

export const PDF: Entry[] = [
  ["merge-pdf", "Merge PDF"],
  ["split-pdf", "Split PDF"],
  ["rotate-pdf", "Rotate PDF"],
  ["organize-pdf", "Organize PDF"],
  ["add-page-numbers", "Page Numbers"],
  ["watermark-pdf", "Watermark"],
  ["crop-pdf", "Crop PDF"],
  ["jpg-to-pdf", "JPG to PDF"],
  ["pdf-to-jpg", "PDF to JPG"],
  ["compress-pdf", "Compress PDF"],
  ["edit-pdf", "Edit PDF"],
  ["sign-pdf", "Sign PDF"],
  ["redact-pdf", "Redact PDF"],
  ["pdf-forms", "Fill Forms"],
  ["protect-pdf", "Protect PDF"],
  ["unlock-pdf", "Unlock PDF"],
  ["compare-pdf", "Compare PDF"],
  ["pdf-to-markdown", "PDF to Markdown"],
  ["scan-to-pdf", "Scan to PDF"],
  ["pdf-to-word", "PDF to Word"],
  ["pdf-to-excel", "PDF to Excel"],
  ["pdf-to-powerpoint", "PDF to PowerPoint"],
  ["word-to-pdf", "Word to PDF"],
  ["excel-to-pdf", "Excel to PDF"],
  ["powerpoint-to-pdf", "PowerPoint to PDF"],
  ["ocr-pdf", "OCR PDF"],
  ["pdf-to-pdfa", "PDF to PDF/A"],
  ["repair-pdf", "Repair PDF"],
  ["html-to-pdf", "HTML to PDF"],
  ["pdf-to-png", "PDF to PNG"],
  ["png-to-pdf", "PNG to PDF"],
  ["pdf-to-text", "PDF to Text"],
  ["delete-pages-from-pdf", "Delete PDF Pages"],
  ["extract-pages-from-pdf", "Extract PDF Pages"],
];

export const PDF_CATEGORY: Record<string, string> = {
  ["merge-pdf"]: "Organize",
  ["split-pdf"]: "Organize",
  ["rotate-pdf"]: "Organize",
  ["organize-pdf"]: "Organize",
  ["add-page-numbers"]: "Edit & Sign",
  ["watermark-pdf"]: "Edit & Sign",
  ["crop-pdf"]: "Edit & Sign",
  ["jpg-to-pdf"]: "Convert",
  ["pdf-to-jpg"]: "Convert",
  ["compress-pdf"]: "Convert",
  ["edit-pdf"]: "Edit & Sign",
  ["sign-pdf"]: "Edit & Sign",
  ["redact-pdf"]: "Security",
  ["pdf-forms"]: "Edit & Sign",
  ["protect-pdf"]: "Security",
  ["unlock-pdf"]: "Security",
  ["compare-pdf"]: "More",
  ["pdf-to-markdown"]: "Convert",
  ["scan-to-pdf"]: "More",
  ["pdf-to-word"]: "Convert",
  ["pdf-to-excel"]: "Convert",
  ["pdf-to-powerpoint"]: "Convert",
  ["word-to-pdf"]: "Convert",
  ["excel-to-pdf"]: "Convert",
  ["powerpoint-to-pdf"]: "Convert",
  ["ocr-pdf"]: "More",
  ["pdf-to-pdfa"]: "More",
  ["repair-pdf"]: "More",
  ["html-to-pdf"]: "Convert",
  ["pdf-to-png"]: "Convert",
  ["png-to-pdf"]: "Convert",
  ["pdf-to-text"]: "Convert",
  ["delete-pages-from-pdf"]: "Organize",
  ["extract-pages-from-pdf"]: "Organize",
};

export const IMAGE_CORE: Entry[] = [
  ["compress-image", "Compress Image"],
  ["resize-image", "Resize Image"],
  ["crop-image", "Crop Image"],
  ["image-converter", "Image Converter"],
];

export const IMAGE_PAIRS: Entry[] = [
  ["jpg-to-png", "JPG to PNG"],
  ["jpg-to-webp", "JPG to WEBP"],
  ["jpg-to-ico", "JPG to ICO"],
  ["png-to-jpg", "PNG to JPG"],
  ["png-to-webp", "PNG to WEBP"],
  ["png-to-ico", "PNG to ICO"],
  ["webp-to-jpg", "WEBP to JPG"],
  ["webp-to-png", "WEBP to PNG"],
  ["webp-to-ico", "WEBP to ICO"],
  ["heic-to-jpg", "HEIC to JPG"],
  ["heic-to-png", "HEIC to PNG"],
  ["heic-to-webp", "HEIC to WEBP"],
  ["heic-to-ico", "HEIC to ICO"],
  ["avif-to-jpg", "AVIF to JPG"],
  ["avif-to-png", "AVIF to PNG"],
  ["avif-to-webp", "AVIF to WEBP"],
  ["avif-to-ico", "AVIF to ICO"],
  ["gif-to-jpg", "GIF to JPG"],
  ["gif-to-png", "GIF to PNG"],
  ["gif-to-webp", "GIF to WEBP"],
  ["gif-to-ico", "GIF to ICO"],
  ["bmp-to-jpg", "BMP to JPG"],
  ["bmp-to-png", "BMP to PNG"],
  ["bmp-to-webp", "BMP to WEBP"],
  ["bmp-to-ico", "BMP to ICO"],
  ["svg-to-jpg", "SVG to JPG"],
  ["svg-to-png", "SVG to PNG"],
  ["svg-to-webp", "SVG to WEBP"],
  ["svg-to-ico", "SVG to ICO"],
];

export const QR_TYPES: Entry[] = [
  ["url-qr-code", "URL"],
  ["text-qr-code", "Text"],
  ["wifi-qr-code", "WiFi"],
  ["vcard-qr-code", "vCard"],
  ["email-qr-code", "Email"],
  ["sms-qr-code", "SMS"],
  ["phone-qr-code", "Phone"],
  ["location-qr-code", "Location"],
];

export const BARCODES: Entry[] = [
  ["barcode-generator", "All formats"],
  ["code-128-barcode-generator", "CODE128"],
  ["ean-13-barcode-generator", "EAN-13"],
  ["upc-a-barcode-generator", "UPC-A"],
  ["code-39-barcode-generator", "CODE39"],
];

export const QR_GUIDES: Entry[] = [
  ["duitnow-qr-code", "DuitNow QR (Malaysia)"],
  ["paynow-qr-code", "PayNow QR (Singapore)"],
  ["upi-qr-code", "UPI QR (India)"],
  ["promptpay-qr-code", "PromptPay QR (Thailand)"],
];

export const TOTAL_PAGES = 135;
